---
- name: Install
  ansible.builtin.package:
    name:
      - open-vm-tools
    state: latest
  become: true

- name: Enable vmtoolsd
  ansible.builtin.systemd:
    enabled: true
    name: vmtoolsd
    state: started
  become: true

- name: Enable vmware-vmblock-fuse
  ansible.builtin.systemd:
    enabled: true
    name: vmware-vmblock-fuse
    state: started
  become: true
