---
- hosts: localhost
  connection: local
  tasks:
    - name: set roles
      set_fact: 
        roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles }}"
      tags:
        - always
    - name: run roles
      include_role:
        apply:
          tags: "{{ item }}"
        name: "{{ item }}"
      with_items: "{{ roles }}"
      tags:
        - always

    - name: run extras
      when: run_extra_roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ extra_roles }}"



