---
- name: Copy i3 config
  ansible.builtin.copy:
    src: "i3/config"
    dest: "{{ ansible_user_dir }}/.config/i3/config"

- name: Copy urxvt config
  ansible.builtin.copy:
    src: ".urxvt"
    dest: "{{ ansible_user_dir }}/.urxvt"

- name: Copy Xresources
  ansible.builtin.copy:
    src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
  notify: reload xrdb


